import { request } from '../lib/apiClient'; // Import the new API client

// Interfaces remain the same as they define the shape of CapexRequest data
export interface CapexRequestUpdate {
  projectName?: string;
  category?: string;
  budgetReference?: string;
  amount?: number;
  startDate?: string;
  endDate?: string;
  status?: 'draft' | 'pending' | 'approved' | 'rejected'; // Consider if these statuses align with backend
  projectLead?: string;
  department?: string;
  subDepartment?: string;
  designConsultant?: string;
  mainContractor?: string;
  description?: string;
  titleArea?: string;
  remarks?: string;
  currentStep?: number; // Workflow related, might be updated via workflow actions
  // updatedBy should be handled by backend from JWT
}

export interface CapexRequest {
  id: string;
  propertyId: string;
  budgetId: string;
  projectName: string;
  category: string;
  budgetReference: string;
  amount: number;
  startDate: string;
  endDate: string;
  status: 'draft' | 'pending' | 'approved' | 'rejected' | 'pending_approval' | 'in_progress' | 'completed' | 'on_hold' | 'cancelled'; // Expanded based on schema.sql
  projectLead: string;
  department: string;
  subDepartment?: string; // Was optional in schema
  designConsultant?: string;
  mainContractor?: string;
  description: string;
  titleArea?: string; // Was optional in schema
  remarks?: string;
  workflowId?: string; // Optional in schema, can be null
  currentStep?: number; // Optional in schema
  createdAt: string;
  createdBy?: string; // Optional, backend might fill this
  updatedAt?: string; // Optional
  updatedBy?: string; // Optional, backend might fill this
}

// Helper to map backend capex request data to frontend CapexRequest type if needed.
// For now, assuming direct compatibility for simplicity or backend aligns with this.
const mapToFrontendCapex = (data: any): CapexRequest => {
  return {
    id: data.id,
    propertyId: data.property_id, // Map from property_id
    budgetId: data.budget_id,
    projectName: data.project_name,
    category: data.category,
    budgetReference: data.budget_reference,
    amount: parseFloat(data.amount) || 0, // Ensure numeric
    startDate: data.start_date,
    endDate: data.end_date,
    status: data.status,
    projectLead: data.project_lead,
    department: data.department,
    subDepartment: data.sub_department,
    designConsultant: data.design_consultant,
    mainContractor: data.main_contractor,
    description: data.description,
    titleArea: data.title_area,
    remarks: data.remarks,
    workflowId: data.workflow_id,
    currentStep: data.current_step,
    createdAt: data.created_at,
    createdBy: data.created_by,
    updatedAt: data.updated_at,
    updatedBy: data.updated_by,
  };
};


export const loadCapexRequests = async (
  propertyId: string,
  status?: 'draft' | 'pending' | 'approved' | 'rejected' // Keep frontend statuses for filtering if desired
): Promise<CapexRequest[]> => {
  // TODO: Define backend API endpoint for fetching capex requests.
  // Example: GET /api/properties/${propertyId}/capex-requests?status=${status}
  // Or GET /api/capex-requests?propertyId=${propertyId}&status=${status}
  try {
    let endpoint = `/api/capex-requests?propertyId=${propertyId}`;
    if (status) {
      endpoint += `&status=${status}`;
    }
    // Assuming the backend returns an array of objects matching the CapexRequest structure (after mapping)
    const data = await request<any[]>(endpoint, { method: 'GET' });
    return data.map(mapToFrontendCapex);
  } catch (error) {
    console.error('Error loading CAPEX requests via API:', error);
    // Fallback to empty array or throw error as per application's error handling strategy
    return [];
  }
};

export const createCapexRequest = async (
  // Omit fields that are auto-generated by backend or come from JWT (createdBy, id, createdAt, updatedAt, updatedBy)
  requestData: Omit<CapexRequest, 'id' | 'createdAt' | 'createdBy' | 'updatedAt' | 'updatedBy' | 'status' | 'currentStep' | 'workflowId'> & { status?: CapexRequest['status'] }
): Promise<CapexRequest | null> => {
  // TODO: Define backend API endpoint for creating a capex request.
  // Example: POST /api/capex-requests
  // Backend should handle setting createdBy from JWT, createdAt, etc.
  try {
    // Map frontend field names to backend field names if they differ
    const payload = {
      property_id: requestData.propertyId,
      budget_id: requestData.budgetId,
      project_name: requestData.projectName,
      category: requestData.category,
      budget_reference: requestData.budgetReference,
      amount: requestData.amount,
      start_date: requestData.startDate,
      end_date: requestData.endDate,
      status: requestData.status || 'draft', // Default status
      project_lead: requestData.projectLead,
      department: requestData.department,
      sub_department: requestData.subDepartment,
      design_consultant: requestData.designConsultant,
      main_contractor: requestData.mainContractor,
      description: requestData.description,
      title_area: requestData.titleArea,
      remarks: requestData.remarks,
      // workflowId and currentStep might be set initially by backend if a default workflow starts
    };
    const data = await request<any>('/api/capex-requests', { // Replace any with backend response type
      method: 'POST',
      body: payload,
    });
    return mapToFrontendCapex(data);
  } catch (error) {
    console.error('Error creating CAPEX request via API:', error);
    return null;
  }
};

export const updateCapexRequest = async (
  id: string,
  updates: CapexRequestUpdate // Frontend sends only the fields it wants to update
): Promise<CapexRequest | null> => { // Return updated request or boolean
  // TODO: Define backend API endpoint for updating a capex request.
  // Example: PATCH /api/capex-requests/${id}
  // Backend should handle updatedBy from JWT and updatedAt.
  try {
     // Map frontend field names to backend field names for the payload
    const payload: any = {};
    if (updates.projectName !== undefined) payload.project_name = updates.projectName;
    if (updates.category !== undefined) payload.category = updates.category;
    if (updates.budgetReference !== undefined) payload.budget_reference = updates.budgetReference;
    if (updates.amount !== undefined) payload.amount = updates.amount;
    if (updates.startDate !== undefined) payload.start_date = updates.startDate;
    if (updates.endDate !== undefined) payload.end_date = updates.endDate;
    if (updates.status !== undefined) payload.status = updates.status;
    if (updates.projectLead !== undefined) payload.project_lead = updates.projectLead;
    if (updates.department !== undefined) payload.department = updates.department;
    if (updates.subDepartment !== undefined) payload.sub_department = updates.subDepartment;
    if (updates.designConsultant !== undefined) payload.design_consultant = updates.designConsultant;
    if (updates.mainContractor !== undefined) payload.main_contractor = updates.mainContractor;
    if (updates.description !== undefined) payload.description = updates.description;
    if (updates.titleArea !== undefined) payload.title_area = updates.titleArea;
    if (updates.remarks !== undefined) payload.remarks = updates.remarks;
    // currentStep and workflowId are typically updated via workflow actions, not direct PATCH here.

    const data = await request<any>(`/api/capex-requests/${id}`, { // Replace any with backend response type
      method: 'PATCH',
      body: payload,
    });
    return mapToFrontendCapex(data);
  } catch (error) {
    console.error(`Error updating CAPEX request ${id} via API:`, error);
    return null; // Or throw error
  }
};

export const deleteCapexRequest = async (id: string): Promise<boolean> => {
  // TODO: Define backend API endpoint for deleting a capex request.
  // Example: DELETE /api/capex-requests/${id}
  try {
    await request<void>(`/api/capex-requests/${id}`, { method: 'DELETE' });
    return true;
  } catch (error) {
    console.error(`Error deleting CAPEX request ${id} via API:`, error);
    return false;
  }
};